import type { Metadata } from "next";
import { Oxanium, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

// Setup Oxanium untuk Heading
const oxanium = Oxanium({
  subsets: ["latin"],
  variable: "--font-oxanium", // Kita bikin CSS Variable
  display: "swap",
});

// Setup Montserrat untuk Body/Konten
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Amerta Teknologi Media",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png?v=1",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${oxanium.variable} ${montserrat.variable}`}>
      <body className="font-sans">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
